name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    env:
      MIX_ENV: test
    strategy:
      matrix:
        otp: ['26.2.5.15', '27.3.4.3']
        elixir: ['1.16.3', '1.17.3', '1.18.4']
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install dependencies
        run: mix deps.get
      - name: Compile application
        run: mix compile --force --warnings-as-errors
      - name: Run tests
        run: mix test
